services:
  - type: web
    name: turbo-mobile-5-backend
    env: python
    region: frankfurt
    plan: free
    rootDir: .
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
